import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {
  const listaMock = [
    'tomar remedio para não dormir',
    'fazer cafe rancheiro',
    'estudar javascript',
    'jogar video game',
  ];

  const [lista, setLista] = useState(listaMock);
  const [item, setItem] = useState('');

  const adicionarItens = (evento) => {
    evento.preventDefault();
    console.log('adicionarItens');

    setLista([...lista, item]);
    setItem('')
    console.log(lista);
  };

  const alterarItem = (evento) => {
    setItem(evento.target.value);
  };

  const removerItem = (posicao) => {
    const novaLista = lista.filter((item, index) => index != posicao);
    setLista(novaLista);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Next to do</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>To do list - Next</h1>
      <form onSubmit={adicionarItens}>
        <input type="text" autoFocus value={item} onChange={alterarItem} autoFocus />
        <button type="submit">Adicionar</button>
      </form>
      <ul>
        {lista.map((item, posicao) => (
          <li key={posicao}>
            {item}
            <button onClick={() => removerItem(posicao)}>Remover</button>
          </li>
        ))}
      </ul>
    </div>
)
}
